name = "Scoot's Friendpack"
author = "Scott"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7fc1adaa0de14e1a787b03d2e810d1256dc7ef5013337f037661a444f47b63df"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1", "1.19.3"]
