name = "Scoot's Friendpack"
author = "Scott"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ebf99b745b174c0db8700084df331d26152b47da678c9327fe164641a46230e"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
